# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cp_char_sheet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CharacterImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.CharacterImage.setGeometry(QtCore.QRect(10, 10, 131, 121))
        self.CharacterImage.setStyleSheet("border: 2px solid rgb(244,0,0);")
        self.CharacterImage.setObjectName("CharacterImage")
        self.handleLabel = QtWidgets.QLabel(self.centralwidget)
        self.handleLabel.setGeometry(QtCore.QRect(160, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.handleLabel.setFont(font)
        self.handleLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.handleLabel.setObjectName("handleLabel")
        self.HandleInput = QtWidgets.QLineEdit(self.centralwidget)
        self.HandleInput.setGeometry(QtCore.QRect(160, 30, 301, 41))
        self.HandleInput.setStyleSheet("background-color: white;\n"
"font: 14pt \"OCR A Extended\";\n"
"border: 2px solid  rgb(244,0,0);\n"
"padding-left: 2px;")
        self.HandleInput.setObjectName("HandleInput")
        self.ImagLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImagLabel.setGeometry(QtCore.QRect(10, 130, 131, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.ImagLabel.setFont(font)
        self.ImagLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;\n"
"")
        self.ImagLabel.setObjectName("ImagLabel")
        self.RoleLabel = QtWidgets.QLabel(self.centralwidget)
        self.RoleLabel.setGeometry(QtCore.QRect(160, 90, 61, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.RoleLabel.setFont(font)
        self.RoleLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.RoleLabel.setObjectName("RoleLabel")
        self.RoleSelect = QtWidgets.QComboBox(self.centralwidget)
        self.RoleSelect.setGeometry(QtCore.QRect(160, 110, 301, 41))
        self.RoleSelect.setAutoFillBackground(False)
        self.RoleSelect.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"background-color: white;\n"
"font: 12pt \"OCR A Extended\";")
        self.RoleSelect.setObjectName("RoleSelect")
        self.RoleAbilityLabel = QtWidgets.QLabel(self.centralwidget)
        self.RoleAbilityLabel.setGeometry(QtCore.QRect(160, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.RoleAbilityLabel.setFont(font)
        self.RoleAbilityLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.RoleAbilityLabel.setObjectName("RoleAbilityLabel")
        self.RoleAbilityDisplay = QtWidgets.QLabel(self.centralwidget)
        self.RoleAbilityDisplay.setGeometry(QtCore.QRect(160, 190, 242, 41))
        self.RoleAbilityDisplay.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"font: 12pt \"OCR A Extended\";\n"
"padding-left: 2px;\n"
"background: white;")
        self.RoleAbilityDisplay.setObjectName("RoleAbilityDisplay")
        self.RankLabel = QtWidgets.QLabel(self.centralwidget)
        self.RankLabel.setGeometry(QtCore.QRect(400, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.RankLabel.setFont(font)
        self.RankLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.RankLabel.setObjectName("RankLabel")
        self.RoleAbilityRankInput = QtWidgets.QLineEdit(self.centralwidget)
        self.RoleAbilityRankInput.setGeometry(QtCore.QRect(400, 190, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RoleAbilityRankInput.setFont(font)
        self.RoleAbilityRankInput.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(244,0,0);\n"
"")
        self.RoleAbilityRankInput.setAlignment(QtCore.Qt.AlignCenter)
        self.RoleAbilityRankInput.setObjectName("RoleAbilityRankInput")
        self.HumanityLabel = QtWidgets.QLabel(self.centralwidget)
        self.HumanityLabel.setGeometry(QtCore.QRect(10, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.HumanityLabel.setFont(font)
        self.HumanityLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.HumanityLabel.setObjectName("HumanityLabel")
        self.HumanityCurrent = QtWidgets.QLabel(self.centralwidget)
        self.HumanityCurrent.setGeometry(QtCore.QRect(10, 190, 61, 41))
        self.HumanityCurrent.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"font: 12pt \"OCR A Extended\";\n"
"padding-left: 2px;\n"
"text-align: center;\n"
"background: white;")
        self.HumanityCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.HumanityCurrent.setObjectName("HumanityCurrent")
        self.HumanitySpacer = QtWidgets.QLabel(self.centralwidget)
        self.HumanitySpacer.setGeometry(QtCore.QRect(70, 190, 10, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.HumanitySpacer.setFont(font)
        self.HumanitySpacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HumanitySpacer.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 8pt \"OCR A Extended\";\n"
"font-weight: bold;")
        self.HumanitySpacer.setObjectName("HumanitySpacer")
        self.HumanityMax = QtWidgets.QLabel(self.centralwidget)
        self.HumanityMax.setGeometry(QtCore.QRect(80, 190, 61, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HumanityMax.setFont(font)
        self.HumanityMax.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"font: 12pt \"OCR A Extended\";\n"
"padding-left: 2px;\n"
"background: white;")
        self.HumanityMax.setAlignment(QtCore.Qt.AlignCenter)
        self.HumanityMax.setObjectName("HumanityMax")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 250, 691, 81))
        self.frame.setStyleSheet("background-color: rgb(244,0,0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.IntelligenceInput = QtWidgets.QLineEdit(self.frame)
        self.IntelligenceInput.setGeometry(QtCore.QRect(10, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.IntelligenceInput.setFont(font)
        self.IntelligenceInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.IntelligenceInput.setAlignment(QtCore.Qt.AlignCenter)
        self.IntelligenceInput.setObjectName("IntelligenceInput")
        self.IntelligenceLabel = QtWidgets.QLabel(self.frame)
        self.IntelligenceLabel.setGeometry(QtCore.QRect(10, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.IntelligenceLabel.setFont(font)
        self.IntelligenceLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.IntelligenceLabel.setObjectName("IntelligenceLabel")
        self.ReflexInput = QtWidgets.QLineEdit(self.frame)
        self.ReflexInput.setGeometry(QtCore.QRect(70, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ReflexInput.setFont(font)
        self.ReflexInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.ReflexInput.setAlignment(QtCore.Qt.AlignCenter)
        self.ReflexInput.setObjectName("ReflexInput")
        self.ReflexLabel = QtWidgets.QLabel(self.frame)
        self.ReflexLabel.setGeometry(QtCore.QRect(70, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.ReflexLabel.setFont(font)
        self.ReflexLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.ReflexLabel.setObjectName("ReflexLabel")
        self.DexterityInput = QtWidgets.QLineEdit(self.frame)
        self.DexterityInput.setGeometry(QtCore.QRect(130, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DexterityInput.setFont(font)
        self.DexterityInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.DexterityInput.setAlignment(QtCore.Qt.AlignCenter)
        self.DexterityInput.setObjectName("DexterityInput")
        self.DexterityLabel = QtWidgets.QLabel(self.frame)
        self.DexterityLabel.setGeometry(QtCore.QRect(130, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.DexterityLabel.setFont(font)
        self.DexterityLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.DexterityLabel.setObjectName("DexterityLabel")
        self.DexterityInput_2 = QtWidgets.QLineEdit(self.frame)
        self.DexterityInput_2.setGeometry(QtCore.QRect(190, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DexterityInput_2.setFont(font)
        self.DexterityInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.DexterityInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DexterityInput_2.setObjectName("DexterityInput_2")
        self.DexterityLabel_2 = QtWidgets.QLabel(self.frame)
        self.DexterityLabel_2.setGeometry(QtCore.QRect(190, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.DexterityLabel_2.setFont(font)
        self.DexterityLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.DexterityLabel_2.setObjectName("DexterityLabel_2")
        self.CoolInput = QtWidgets.QLineEdit(self.frame)
        self.CoolInput.setGeometry(QtCore.QRect(250, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CoolInput.setFont(font)
        self.CoolInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.CoolInput.setAlignment(QtCore.Qt.AlignCenter)
        self.CoolInput.setObjectName("CoolInput")
        self.BodyLabel_2 = QtWidgets.QLineEdit(self.frame)
        self.BodyLabel_2.setGeometry(QtCore.QRect(430, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.BodyLabel_2.setFont(font)
        self.BodyLabel_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.BodyLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.CoolLabel = QtWidgets.QLabel(self.frame)
        self.CoolLabel.setGeometry(QtCore.QRect(250, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.CoolLabel.setFont(font)
        self.CoolLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.CoolLabel.setObjectName("CoolLabel")
        self.WillInput = QtWidgets.QLineEdit(self.frame)
        self.WillInput.setGeometry(QtCore.QRect(310, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.WillInput.setFont(font)
        self.WillInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.WillInput.setAlignment(QtCore.Qt.AlignCenter)
        self.WillInput.setObjectName("WillInput")
        self.WillLabel = QtWidgets.QLabel(self.frame)
        self.WillLabel.setGeometry(QtCore.QRect(310, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.WillLabel.setFont(font)
        self.WillLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.WillLabel.setObjectName("WillLabel")
        self.MoveInput = QtWidgets.QLineEdit(self.frame)
        self.MoveInput.setGeometry(QtCore.QRect(370, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MoveInput.setFont(font)
        self.MoveInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.MoveInput.setAlignment(QtCore.Qt.AlignCenter)
        self.MoveInput.setObjectName("MoveInput")
        self.MoveLabel = QtWidgets.QLabel(self.frame)
        self.MoveLabel.setGeometry(QtCore.QRect(370, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.MoveLabel.setFont(font)
        self.MoveLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.MoveLabel.setObjectName("MoveLabel")
        self.BodyLabel = QtWidgets.QLabel(self.frame)
        self.BodyLabel.setGeometry(QtCore.QRect(430, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.BodyLabel.setObjectName("BodyLabel")
        self.LuckLabel = QtWidgets.QLabel(self.frame)
        self.LuckLabel.setGeometry(QtCore.QRect(490, 7, 91, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.LuckLabel.setFont(font)
        self.LuckLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.LuckLabel.setObjectName("LuckLabel")
        self.LuckCurrentInput = QtWidgets.QLineEdit(self.frame)
        self.LuckCurrentInput.setGeometry(QtCore.QRect(490, 29, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LuckCurrentInput.setFont(font)
        self.LuckCurrentInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.LuckCurrentInput.setAlignment(QtCore.Qt.AlignCenter)
        self.LuckCurrentInput.setObjectName("LuckCurrentInput")
        self.LuckMaxInput = QtWidgets.QLineEdit(self.frame)
        self.LuckMaxInput.setGeometry(QtCore.QRect(540, 29, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LuckMaxInput.setFont(font)
        self.LuckMaxInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.LuckMaxInput.setAlignment(QtCore.Qt.AlignCenter)
        self.LuckMaxInput.setObjectName("LuckMaxInput")
        self.LuckSpacer = QtWidgets.QLabel(self.frame)
        self.LuckSpacer.setGeometry(QtCore.QRect(530, 29, 10, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.LuckSpacer.setFont(font)
        self.LuckSpacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LuckSpacer.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 8pt \"OCR A Extended\";\n"
"font-weight: bold;")
        self.LuckSpacer.setObjectName("LuckSpacer")
        self.EmpathySpacer = QtWidgets.QLabel(self.frame)
        self.EmpathySpacer.setGeometry(QtCore.QRect(630, 30, 10, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.EmpathySpacer.setFont(font)
        self.EmpathySpacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EmpathySpacer.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 8pt \"OCR A Extended\";\n"
"font-weight: bold;")
        self.EmpathySpacer.setObjectName("EmpathySpacer")
        self.EmpathyMaxInput = QtWidgets.QLineEdit(self.frame)
        self.EmpathyMaxInput.setGeometry(QtCore.QRect(640, 30, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EmpathyMaxInput.setFont(font)
        self.EmpathyMaxInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.EmpathyMaxInput.setAlignment(QtCore.Qt.AlignCenter)
        self.EmpathyMaxInput.setObjectName("EmpathyMaxInput")
        self.EmpathyLabel = QtWidgets.QLabel(self.frame)
        self.EmpathyLabel.setGeometry(QtCore.QRect(590, 8, 91, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.EmpathyLabel.setFont(font)
        self.EmpathyLabel.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.EmpathyLabel.setObjectName("EmpathyLabel")
        self.EmpathyCurrentInput = QtWidgets.QLineEdit(self.frame)
        self.EmpathyCurrentInput.setGeometry(QtCore.QRect(590, 30, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EmpathyCurrentInput.setFont(font)
        self.EmpathyCurrentInput.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.EmpathyCurrentInput.setAlignment(QtCore.Qt.AlignCenter)
        self.EmpathyCurrentInput.setObjectName("EmpathyCurrentInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cyberpunk Red Character Sheet"))
        self.handleLabel.setText(_translate("MainWindow", "HANDLE"))
        self.ImagLabel.setText(_translate("MainWindow", "IMAGE"))
        self.RoleLabel.setText(_translate("MainWindow", "ROLES"))
        self.RoleAbilityLabel.setText(_translate("MainWindow", "ROLE ABILITY"))
        self.RoleAbilityDisplay.setText(_translate("MainWindow", "No role selected..."))
        self.RankLabel.setText(_translate("MainWindow", "RANK"))
        self.RoleAbilityRankInput.setText(_translate("MainWindow", "4"))
        self.HumanityLabel.setText(_translate("MainWindow", "HUMANITY"))
        self.HumanityCurrent.setText(_translate("MainWindow", "23"))
        self.HumanitySpacer.setText(_translate("MainWindow", "|"))
        self.HumanityMax.setText(_translate("MainWindow", "23"))
        self.IntelligenceInput.setText(_translate("MainWindow", "8"))
        self.IntelligenceLabel.setText(_translate("MainWindow", "INT"))
        self.ReflexInput.setText(_translate("MainWindow", "6"))
        self.ReflexLabel.setText(_translate("MainWindow", "REF"))
        self.DexterityInput.setText(_translate("MainWindow", "5"))
        self.DexterityLabel.setText(_translate("MainWindow", "DEX"))
        self.DexterityInput_2.setText(_translate("MainWindow", "8"))
        self.DexterityLabel_2.setText(_translate("MainWindow", "TECH"))
        self.CoolInput.setText(_translate("MainWindow", "5"))
        self.BodyLabel_2.setText(_translate("MainWindow", "5"))
        self.CoolLabel.setText(_translate("MainWindow", "COOL"))
        self.WillInput.setText(_translate("MainWindow", "5"))
        self.WillLabel.setText(_translate("MainWindow", "WILL"))
        self.MoveInput.setText(_translate("MainWindow", "5"))
        self.MoveLabel.setText(_translate("MainWindow", "MOVE"))
        self.BodyLabel.setText(_translate("MainWindow", "BODY"))
        self.LuckLabel.setText(_translate("MainWindow", "LUCK"))
        self.LuckCurrentInput.setText(_translate("MainWindow", "7"))
        self.LuckMaxInput.setText(_translate("MainWindow", "7"))
        self.LuckSpacer.setText(_translate("MainWindow", "|"))
        self.EmpathySpacer.setText(_translate("MainWindow", "|"))
        self.EmpathyMaxInput.setText(_translate("MainWindow", "8"))
        self.EmpathyLabel.setText(_translate("MainWindow", "EMP"))
        self.EmpathyCurrentInput.setText(_translate("MainWindow", "7"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
