# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cp_char_sheet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(10, 10, 1101, 671))
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.charSheetGroup = QtWidgets.QGroupBox(self.subwindow)
        self.charSheetGroup.setGeometry(QtCore.QRect(20, 30, 1051, 591))
        self.charSheetGroup.setObjectName("charSheetGroup")
        self.HandleInput = QtWidgets.QLineEdit(self.charSheetGroup)
        self.HandleInput.setGeometry(QtCore.QRect(160, 40, 301, 41))
        self.HandleInput.setStyleSheet("background-color: white;\n"
"font: 14pt \"OCR A Extended\";\n"
"border: 2px solid  rgb(244,0,0);\n"
"padding-left: 2px;")
        self.HandleInput.setObjectName("HandleInput")
        self.HumanityCurrent = QtWidgets.QLabel(self.charSheetGroup)
        self.HumanityCurrent.setGeometry(QtCore.QRect(10, 200, 61, 41))
        self.HumanityCurrent.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"font: 12pt \"OCR A Extended\";\n"
"padding-left: 2px;\n"
"text-align: center;\n"
"background: white;")
        self.HumanityCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.HumanityCurrent.setObjectName("HumanityCurrent")
        self.handleLabel = QtWidgets.QLabel(self.charSheetGroup)
        self.handleLabel.setGeometry(QtCore.QRect(160, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.handleLabel.setFont(font)
        self.handleLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.handleLabel.setObjectName("handleLabel")
        self.RankLabel = QtWidgets.QLabel(self.charSheetGroup)
        self.RankLabel.setGeometry(QtCore.QRect(400, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.RankLabel.setFont(font)
        self.RankLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.RankLabel.setObjectName("RankLabel")
        self.RoleAbilityDisplay = QtWidgets.QLabel(self.charSheetGroup)
        self.RoleAbilityDisplay.setGeometry(QtCore.QRect(160, 200, 242, 41))
        self.RoleAbilityDisplay.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"font: 12pt \"OCR A Extended\";\n"
"padding-left: 2px;\n"
"background: white;")
        self.RoleAbilityDisplay.setObjectName("RoleAbilityDisplay")
        self.CharacterImage = QtWidgets.QGraphicsView(self.charSheetGroup)
        self.CharacterImage.setGeometry(QtCore.QRect(10, 20, 131, 121))
        self.CharacterImage.setStyleSheet("border: 2px solid rgb(244,0,0);")
        self.CharacterImage.setObjectName("CharacterImage")
        self.HumanityMax = QtWidgets.QLabel(self.charSheetGroup)
        self.HumanityMax.setGeometry(QtCore.QRect(80, 200, 61, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HumanityMax.setFont(font)
        self.HumanityMax.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"font: 12pt \"OCR A Extended\";\n"
"padding-left: 2px;\n"
"background: white;")
        self.HumanityMax.setAlignment(QtCore.Qt.AlignCenter)
        self.HumanityMax.setObjectName("HumanityMax")
        self.RoleLabel = QtWidgets.QLabel(self.charSheetGroup)
        self.RoleLabel.setGeometry(QtCore.QRect(160, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.RoleLabel.setFont(font)
        self.RoleLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.RoleLabel.setObjectName("RoleLabel")
        self.RoleSelect = QtWidgets.QComboBox(self.charSheetGroup)
        self.RoleSelect.setGeometry(QtCore.QRect(160, 120, 301, 41))
        self.RoleSelect.setAutoFillBackground(False)
        self.RoleSelect.setStyleSheet("border: 2px solid rgb(244,0,0);\n"
"background-color: white;\n"
"font: 12pt \"OCR A Extended\";")
        self.RoleSelect.setObjectName("RoleSelect")
        self.HumanityLabel = QtWidgets.QLabel(self.charSheetGroup)
        self.HumanityLabel.setGeometry(QtCore.QRect(10, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.HumanityLabel.setFont(font)
        self.HumanityLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.HumanityLabel.setObjectName("HumanityLabel")
        self.RoleAbilityRankInput = QtWidgets.QLineEdit(self.charSheetGroup)
        self.RoleAbilityRankInput.setGeometry(QtCore.QRect(400, 200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RoleAbilityRankInput.setFont(font)
        self.RoleAbilityRankInput.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(244,0,0);\n"
"")
        self.RoleAbilityRankInput.setAlignment(QtCore.Qt.AlignCenter)
        self.RoleAbilityRankInput.setObjectName("RoleAbilityRankInput")
        self.ImagLabel = QtWidgets.QLabel(self.charSheetGroup)
        self.ImagLabel.setGeometry(QtCore.QRect(10, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.ImagLabel.setFont(font)
        self.ImagLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;\n"
"")
        self.ImagLabel.setObjectName("ImagLabel")
        self.HumanitySpacer = QtWidgets.QLabel(self.charSheetGroup)
        self.HumanitySpacer.setGeometry(QtCore.QRect(70, 200, 10, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.HumanitySpacer.setFont(font)
        self.HumanitySpacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HumanitySpacer.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 8pt \"OCR A Extended\";\n"
"font-weight: bold;")
        self.HumanitySpacer.setObjectName("HumanitySpacer")
        self.RoleAbilityLabel = QtWidgets.QLabel(self.charSheetGroup)
        self.RoleAbilityLabel.setGeometry(QtCore.QRect(160, 180, 121, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.RoleAbilityLabel.setFont(font)
        self.RoleAbilityLabel.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.RoleAbilityLabel.setObjectName("RoleAbilityLabel")
        self.frame = QtWidgets.QFrame(self.charSheetGroup)
        self.frame.setGeometry(QtCore.QRect(10, 260, 691, 81))
        self.frame.setStyleSheet("background-color: rgb(244,0,0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.IntelligenceInput_2 = QtWidgets.QLineEdit(self.frame)
        self.IntelligenceInput_2.setGeometry(QtCore.QRect(10, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.IntelligenceInput_2.setFont(font)
        self.IntelligenceInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.IntelligenceInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.IntelligenceInput_2.setObjectName("IntelligenceInput_2")
        self.IntelligenceLabel_2 = QtWidgets.QLabel(self.frame)
        self.IntelligenceLabel_2.setGeometry(QtCore.QRect(10, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.IntelligenceLabel_2.setFont(font)
        self.IntelligenceLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.IntelligenceLabel_2.setObjectName("IntelligenceLabel_2")
        self.ReflexInput_2 = QtWidgets.QLineEdit(self.frame)
        self.ReflexInput_2.setGeometry(QtCore.QRect(70, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ReflexInput_2.setFont(font)
        self.ReflexInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.ReflexInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ReflexInput_2.setObjectName("ReflexInput_2")
        self.ReflexLabel_2 = QtWidgets.QLabel(self.frame)
        self.ReflexLabel_2.setGeometry(QtCore.QRect(70, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.ReflexLabel_2.setFont(font)
        self.ReflexLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.ReflexLabel_2.setObjectName("ReflexLabel_2")
        self.DexterityInput_2 = QtWidgets.QLineEdit(self.frame)
        self.DexterityInput_2.setGeometry(QtCore.QRect(130, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DexterityInput_2.setFont(font)
        self.DexterityInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.DexterityInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DexterityInput_2.setObjectName("DexterityInput_2")
        self.DexterityLabel_2 = QtWidgets.QLabel(self.frame)
        self.DexterityLabel_2.setGeometry(QtCore.QRect(130, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.DexterityLabel_2.setFont(font)
        self.DexterityLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.DexterityLabel_2.setObjectName("DexterityLabel_2")
        self.TechInput_2 = QtWidgets.QLineEdit(self.frame)
        self.TechInput_2.setGeometry(QtCore.QRect(190, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TechInput_2.setFont(font)
        self.TechInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.TechInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TechInput_2.setObjectName("TechInput_2")
        self.TechLabel_2 = QtWidgets.QLabel(self.frame)
        self.TechLabel_2.setGeometry(QtCore.QRect(190, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.TechLabel_2.setFont(font)
        self.TechLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.TechLabel_2.setObjectName("TechLabel_2")
        self.CoolInput_2 = QtWidgets.QLineEdit(self.frame)
        self.CoolInput_2.setGeometry(QtCore.QRect(250, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CoolInput_2.setFont(font)
        self.CoolInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.CoolInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.CoolInput_2.setObjectName("CoolInput_2")
        self.BodyInput_2 = QtWidgets.QLineEdit(self.frame)
        self.BodyInput_2.setGeometry(QtCore.QRect(430, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.BodyInput_2.setFont(font)
        self.BodyInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.BodyInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BodyInput_2.setObjectName("BodyInput_2")
        self.CoolLabel_2 = QtWidgets.QLabel(self.frame)
        self.CoolLabel_2.setGeometry(QtCore.QRect(250, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.CoolLabel_2.setFont(font)
        self.CoolLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.CoolLabel_2.setObjectName("CoolLabel_2")
        self.WillInput_2 = QtWidgets.QLineEdit(self.frame)
        self.WillInput_2.setGeometry(QtCore.QRect(310, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.WillInput_2.setFont(font)
        self.WillInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.WillInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.WillInput_2.setObjectName("WillInput_2")
        self.WillLabel_2 = QtWidgets.QLabel(self.frame)
        self.WillLabel_2.setGeometry(QtCore.QRect(310, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.WillLabel_2.setFont(font)
        self.WillLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.WillLabel_2.setObjectName("WillLabel_2")
        self.MoveInput_2 = QtWidgets.QLineEdit(self.frame)
        self.MoveInput_2.setGeometry(QtCore.QRect(370, 29, 51, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MoveInput_2.setFont(font)
        self.MoveInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.MoveInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.MoveInput_2.setObjectName("MoveInput_2")
        self.MoveLabel_2 = QtWidgets.QLabel(self.frame)
        self.MoveLabel_2.setGeometry(QtCore.QRect(370, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.MoveLabel_2.setFont(font)
        self.MoveLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.MoveLabel_2.setObjectName("MoveLabel_2")
        self.BodyLabel_2 = QtWidgets.QLabel(self.frame)
        self.BodyLabel_2.setGeometry(QtCore.QRect(430, 7, 51, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.BodyLabel_2.setFont(font)
        self.BodyLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.LuckLabel_2 = QtWidgets.QLabel(self.frame)
        self.LuckLabel_2.setGeometry(QtCore.QRect(490, 7, 91, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.LuckLabel_2.setFont(font)
        self.LuckLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.LuckLabel_2.setObjectName("LuckLabel_2")
        self.LuckCurrentInput_2 = QtWidgets.QLineEdit(self.frame)
        self.LuckCurrentInput_2.setGeometry(QtCore.QRect(490, 29, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LuckCurrentInput_2.setFont(font)
        self.LuckCurrentInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.LuckCurrentInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LuckCurrentInput_2.setObjectName("LuckCurrentInput_2")
        self.LuckMaxInput_2 = QtWidgets.QLineEdit(self.frame)
        self.LuckMaxInput_2.setGeometry(QtCore.QRect(540, 29, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LuckMaxInput_2.setFont(font)
        self.LuckMaxInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.LuckMaxInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LuckMaxInput_2.setObjectName("LuckMaxInput_2")
        self.LuckSpacer_2 = QtWidgets.QLabel(self.frame)
        self.LuckSpacer_2.setGeometry(QtCore.QRect(530, 29, 10, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.LuckSpacer_2.setFont(font)
        self.LuckSpacer_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LuckSpacer_2.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 8pt \"OCR A Extended\";\n"
"font-weight: bold;")
        self.LuckSpacer_2.setObjectName("LuckSpacer_2")
        self.EmpathySpacer_2 = QtWidgets.QLabel(self.frame)
        self.EmpathySpacer_2.setGeometry(QtCore.QRect(630, 30, 10, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.EmpathySpacer_2.setFont(font)
        self.EmpathySpacer_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EmpathySpacer_2.setStyleSheet("background-color: rgb(244, 0, 0);\n"
"color: white;\n"
"font: 8pt \"OCR A Extended\";\n"
"font-weight: bold;")
        self.EmpathySpacer_2.setObjectName("EmpathySpacer_2")
        self.EmpathyMaxInput_2 = QtWidgets.QLineEdit(self.frame)
        self.EmpathyMaxInput_2.setGeometry(QtCore.QRect(640, 30, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EmpathyMaxInput_2.setFont(font)
        self.EmpathyMaxInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.EmpathyMaxInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EmpathyMaxInput_2.setObjectName("EmpathyMaxInput_2")
        self.EmpathyLabel_2 = QtWidgets.QLabel(self.frame)
        self.EmpathyLabel_2.setGeometry(QtCore.QRect(590, 8, 91, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.EmpathyLabel_2.setFont(font)
        self.EmpathyLabel_2.setStyleSheet("background-color:white;\n"
"color: black;\n"
"font: 10pt \"OCR A Extended\";\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.EmpathyLabel_2.setObjectName("EmpathyLabel_2")
        self.EmpathyCurrentInput_2 = QtWidgets.QLineEdit(self.frame)
        self.EmpathyCurrentInput_2.setGeometry(QtCore.QRect(590, 30, 41, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EmpathyCurrentInput_2.setFont(font)
        self.EmpathyCurrentInput_2.setStyleSheet("background-color: white;\n"
"font-weight: bold;\n"
"border: none;")
        self.EmpathyCurrentInput_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EmpathyCurrentInput_2.setObjectName("EmpathyCurrentInput_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cyberpunk Red Character Sheet"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.charSheetGroup.setTitle(_translate("MainWindow", "Player Name Here"))
        self.HumanityCurrent.setText(_translate("MainWindow", "23"))
        self.handleLabel.setText(_translate("MainWindow", "HANDLE"))
        self.RankLabel.setText(_translate("MainWindow", "RANK"))
        self.RoleAbilityDisplay.setText(_translate("MainWindow", "No role selected..."))
        self.HumanityMax.setText(_translate("MainWindow", "23"))
        self.RoleLabel.setText(_translate("MainWindow", "ROLES"))
        self.HumanityLabel.setText(_translate("MainWindow", "HUMANITY"))
        self.RoleAbilityRankInput.setText(_translate("MainWindow", "4"))
        self.ImagLabel.setText(_translate("MainWindow", "IMAGE"))
        self.HumanitySpacer.setText(_translate("MainWindow", "|"))
        self.RoleAbilityLabel.setText(_translate("MainWindow", "ROLE ABILITY"))
        self.IntelligenceInput_2.setText(_translate("MainWindow", "8"))
        self.IntelligenceLabel_2.setText(_translate("MainWindow", "INT"))
        self.ReflexInput_2.setText(_translate("MainWindow", "6"))
        self.ReflexLabel_2.setText(_translate("MainWindow", "REF"))
        self.DexterityInput_2.setText(_translate("MainWindow", "5"))
        self.DexterityLabel_2.setText(_translate("MainWindow", "DEX"))
        self.TechInput_2.setText(_translate("MainWindow", "8"))
        self.TechLabel_2.setText(_translate("MainWindow", "TECH"))
        self.CoolInput_2.setText(_translate("MainWindow", "5"))
        self.BodyInput_2.setText(_translate("MainWindow", "5"))
        self.CoolLabel_2.setText(_translate("MainWindow", "COOL"))
        self.WillInput_2.setText(_translate("MainWindow", "5"))
        self.WillLabel_2.setText(_translate("MainWindow", "WILL"))
        self.MoveInput_2.setText(_translate("MainWindow", "5"))
        self.MoveLabel_2.setText(_translate("MainWindow", "MOVE"))
        self.BodyLabel_2.setText(_translate("MainWindow", "BODY"))
        self.LuckLabel_2.setText(_translate("MainWindow", "LUCK"))
        self.LuckCurrentInput_2.setText(_translate("MainWindow", "7"))
        self.LuckMaxInput_2.setText(_translate("MainWindow", "7"))
        self.LuckSpacer_2.setText(_translate("MainWindow", "|"))
        self.EmpathySpacer_2.setText(_translate("MainWindow", "|"))
        self.EmpathyMaxInput_2.setText(_translate("MainWindow", "8"))
        self.EmpathyLabel_2.setText(_translate("MainWindow", "EMP"))
        self.EmpathyCurrentInput_2.setText(_translate("MainWindow", "7"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
